### ISSUE TITLE
indicate which button was clicked

### ISSUE THREAD

**Issue by getaaron** [ksmithbaylor/vin-barcodes#5]
I see people go to https://www.randomvinbarcode.com and click on the "Real" button even though this is the default

We should have some UI that makes it clear what type of barcode has been generated

**Comment by getaaron** [comment]
# OR JUST DROP SUPPORT FOR FAKE VINS SINCE NOBDY WANTS THEM

**Comment by ksmithbaylor** [comment]
Support for fake VINs has been dropped!

<img width="455" alt="image" src="https://user-images.githubusercontent.com/1709318/52949583-b5ab2700-334a-11e9-89f8-2625b0594e0f.png">
