### ISSUE TITLE
Copy VIN button

### ISSUE THREAD

**Issue by getaaron** [ksmithbaylor/vin-barcodes#6]
We should add a <kbd>Copy VIN</kbd> button.

## Acceptance Criteria

AS A USER WHO LIKES TO COPY THINGS,
WHEN I CLICK THE <kbd>Copy VIN</kbd> BUTTON,
THE VIN IS COPIED TO THE PASTEBOARD,

**Comment by gareys** [comment]
yes, this...

**Comment by getaaron** [comment]
@gareys heres a mockup, plz implement

<img width="211" alt="image" src="https://user-images.githubusercontent.com/789577/49093721-b8f2b300-f232-11e8-96e2-509d54830753.png">

**Comment by ksmithbaylor** [comment]
Ask and you shall receive.

![copy](https://user-images.githubusercontent.com/1709318/52952513-c364aa80-3352-11e9-8010-2c6997a1cf50.gif)

**Comment by getaaron** [comment]
You didn’t like my mock-up?

**Comment by ksmithbaylor** [comment]
`git commit -m "Detect Aaron's computer and serve him the copy button directly from GitHub"`
